# Generated by Django 5.2.7 on 2025-11-05 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Thing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Color.color')),
            ],
        ),
    ]
